- hosts: all
  become: yes
  tasks:
    - name: Ensure that apache is installed
	  yum: 
	    name: httpd 
		state: present
	- name: Ensure that httpd is running
	  service: name=http state=started enabled=yes